helpResponse = [
    {
        "speaker": "system",
        "text": (
            "<div class='help-section'>"
            "<h3>Movement</h3>"
            "<ul>"
            "<li>north or n</li>"
            "<li>south or s</li>"
            "<li>east or e</li>"
            "<li>west or w</li>"
            "</ul>"
            "<h3>Looking</h3>"
            "<p>Describes the area or target.</p>"
            "<ul>"
            "<li>look</li>"
            "<li>look at &lt;target&gt;</li>"
            "</ul>"
            "<h3>Searching</h3>"
            "<p>Finds viewable items or items inside a target.</p>"
            "<ul>"
            "<li>search</li>"
            "<li>search &lt;target&gt;</li>"
            "</ul>"
            "<h3>Inventory</h3>"
            "<p>Shows the items you are currently carrying.</p>"
            "<ul>"
            "<li>inventory, inv, i</li>"
            "<li>bag</li>"
            "</ul>"
            "<h3>Interactions</h3>"
            "<ul>"
            "<li>open &lt;target&gt;</li>"
            "<li>close &lt;target&gt;</li>"
            "<li>use &lt;item&gt; on &lt;target&gt;</li>"
            "<li>throw &lt;item&gt;</li>"
            "<li>throw &lt;item&gt; at &lt;target&gt;</li>"
            "</ul>"
            "<h3>Aliases</h3>"
            "<ul>"
            "<li>grab</li>"
            "<li>get</li>"
            "<li>pick up</li>"
            "<li>inspect</li>"
            "<li>examine</li>"
            "<li>equip</li>"
            "</ul>"
            "</div>"
        ),
    }
]
